# SPDX-License-Identifier: MIT
---
- name: Ensure ansible_facts used by role
  setup:
    gather_subset: min
  when:
    - __mssql_required_facts is defined
    - not ansible_facts.keys() | list |
      intersect(__mssql_required_facts) == __mssql_required_facts

- name: Set platform/version specific variables

  # Load variables from YAML files that are specific to the platform and version of the operating system
  include_vars: "{{ __mssql_vars_file }}"

  # Iterate over a list of YAML files that should be loaded
  loop:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"

  # Set the value of the __mssql_vars_file variable
  vars:
    __mssql_vars_file: "{{ role_path }}/vars/{{ item }}"

  # Only execute the task if the __mssql_vars_file variable is a file
